;;-*-coding: utf-8;-*-
(define-abbrev-table 'rescript-mode-abbrev-table
  '(
    (";ac" "alignItems=Center" nil :count 1)
    (";b" "bool" nil :count 1)
    (";br" "borderRadius=Number(1.)" nil :count 1)
    (";cp" "cursor=Pointer" nil :count 1)
    (";dl" "disabled=isLoading" nil :count 2)
    (";dr" "direction=[Row]" nil :count 2)
    (";e" "( ) => " nil :count 3)
    (";f" "_ => " nil :count 1)
    (";f1" "flex=Number(1.)" nil :count 1)
    (";fg" "flexGrow=Number(1.)" nil :count 1)
    (";gm" "gap=mold(8.)" nil :count 8)
    (";h0" "minHeight=Number(0.)" nil :count 1)
    (";h1" "height=String(\"100%\")" nil :count 8)
    (";ic" "client->ReactQuery.Client.invalidateQueries([\"api\"])" nil :count 6)
    (";jcb" "justifyContent=String(\"space-between\")" nil :count 4)
    (";l" "loading=isLoading" nil :count 2)
    (";mt" "mt={mold(16.)}" nil :count 4)
    (";oc" "open Color" nil :count 4)
    (";om" "open Mui" nil :count 2)
    (";ot" "_ => toggleOpen()" nil :count 3)
    (";ou" "open Ui" nil :count 0)
    (";pm" "p=mold(8.)" nil :count 5)
    (";rc" "let client = ReactQuery.Client.useClient()" nil :count 5)
    (";s" "string" nil :count 2)
    (";sm" "size=Small" nil :count 2)
    (";uc" "let {cred} = Hook.useCreds()" nil :count 5)
    (";ut" "let (isOpen, toggleOpen, _) = Hook.useToggle()" nil :count 4)
    (";w1" "width=String(\"100%\")" nil :count 10)
    (";w6" "weight=Number(600.)" nil :count 10)
    ("S" "Shape" nil :count 5)
   ))

(define-abbrev-table 'typescript-mode-abbrev-table
  '(
    (";a" "Array" nil :count 0)
    (";b" "boolean" nil :count 3)
    (";e" "( ) => " nil :count 0)
    (";n" "number" nil :count 2)
    (";s" "string" nil :count 1)
   ))

(define-abbrev-table 'web-mode-abbrev-table
  '(
    (";a" "Array" nil :count 0)
    (";b" "boolean" nil :count 4)
    (";e" "( ) => " nil :count 3)
    (";h0" "minHeight={0}" nil :count 1)
    (";h1" "height=\"100%\"" nil :count 8)
    (";ld" "loading" nil :count 4)
    (";n" "number" nil :count 0)
    (";one" "onError: (d) => toast.error(d?.message || \"Something went wrong\")" nil :count 4)
    (";s" "string" nil :count 3)
    (";st" "Stack" nil :count 9)
    (";usl" "const [loading, setLoading] = useState(false);" nil :count 5)
    (";w0" "minWidth={0}" nil :count 1)
    (";w1" "width=\"100%\"" nil :count 8)
    (";y" "async" nil :count 5)
   ))

